version: 2.1

orbs: 
  aws-ecr: circleci/aws-ecr@8.1.2

jobs:
  dockerise:
    executor: aws-ecr/default
    resource_class: arm.medium
    steps:
      - aws-ecr/build-and-push-image:
          aws-cli-version: latest
          no-output-timeout: 20m
          platform: linux/amd64
          push-image: true
          checkout: true
          repo: coins
          tag: 'latest'


workflows:
  dev-build:
    jobs:
      - dockerise:
          context: coins-ci
