version: 2.1

orbs: 
  aws-ecr: circleci/aws-ecr@8.1.2
  aws-ecs: circleci/aws-ecs@3.1.0

executors:
  docker-build-executor:
    machine:
      image: ubuntu-2004:current

jobs:
  dockerise:
    # executor: aws-ecr/default
    executor: docker-build-executor
    resource_class: arm.medium
    steps:
      - aws-ecr/build-and-push-image:
          aws-cli-version: latest
          no-output-timeout: 20m
          platform: linux/arm64
          push-image: true
          checkout: true
          repo: coins
          tag: ${CIRCLE_SHA1}

workflows:
  dev-build:
    jobs:
      - dockerise:
          context: coins-ci
      - aws-ecs/deploy-service-update:
          container-image-name-updates: 'container=app,tag=${CIRCLE_SHA1}'
          cluster: dev
          family: coins
          context: coins-ci
          service-name: dev-coins-service 
          requires:
            - dockerise
